name: panjatan_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  bloc: ^8.1.4
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_bloc: ^8.1.6  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
